apiVersion: v1
kind: Secret
metadata:
  name: aivillage-secrets
  namespace: aivillage-production
type: Opaque
stringData:
  # Database passwords (base64 encoded in production)
  POSTGRES_PASSWORD: "REPLACE_WITH_PRODUCTION_PASSWORD"
  REDIS_PASSWORD: "REPLACE_WITH_PRODUCTION_REDIS_PASSWORD"
  NEO4J_PASSWORD: "REPLACE_WITH_PRODUCTION_NEO4J_PASSWORD"

  # JWT secrets
  HYPERAG_JWT_SECRET: "REPLACE_WITH_PRODUCTION_JWT_SECRET"

  # API keys
  OPENAI_API_KEY: "REPLACE_WITH_OPENAI_API_KEY"
  ANTHROPIC_API_KEY: "REPLACE_WITH_ANTHROPIC_API_KEY"

  # Monitoring
  GRAFANA_PASSWORD: "REPLACE_WITH_GRAFANA_PASSWORD"

---
apiVersion: v1
kind: Secret
metadata:
  name: aivillage-secrets
  namespace: aivillage-staging
type: Opaque
stringData:
  # Database passwords
  POSTGRES_PASSWORD: "${POSTGRES_PASSWORD}"
  REDIS_PASSWORD: "${REDIS_PASSWORD}"
  NEO4J_PASSWORD: "${NEO4J_PASSWORD}"

  # JWT secrets
  HYPERAG_JWT_SECRET: "${HYPERAG_JWT_SECRET}"

  # API keys (use test keys for staging)
  OPENAI_API_KEY: "${OPENAI_API_KEY}"
  ANTHROPIC_API_KEY: "${ANTHROPIC_API_KEY}"

  # Monitoring
  GRAFANA_PASSWORD: "${GRAFANA_PASSWORD}"
