#!/usr/bin/env python3
"""
Guard Tests Package Initialization
==================================

Initializes comprehensive guard test suite for preventing regression
in all Phase 4 security, performance, and integration fixes.

Generated by TDD London School Swarm Agent for Phase 5 guard protection.
"""

import sys
from pathlib import Path

# Add src to Python path for imports
PROJECT_ROOT = Path(__file__).parent.parent.parent
sys.path.insert(0, str(PROJECT_ROOT / "src"))

# Guard test categories
GUARD_CATEGORIES = {
    "security": [
        "test_cors_config_regression",
        "test_websocket_security_regression"
    ],
    "performance": [
        "test_caching_performance_regression"
    ],
    "imports": [
        "test_grokfast_import_regression"
    ],
    "integration": [
        "test_localhost_admin_security_integration",
        "test_core_blocker_fixes_integration", 
        "test_configuration_integrity_guards"
    ],
    "monitoring": [
        "test_continuous_guard_monitoring"
    ]
}

# Critical protection areas
CRITICAL_PROTECTIONS = [
    "CORS wildcard prevention",
    "WebSocket RCE blocking", 
    "Admin localhost-only binding",
    "GrokFast import resolution",
    "Redis connection pooling",
    "Core blocker workflow integrity",
    "Configuration security validation"
]

__version__ = "1.0.0"
__author__ = "TDD London School Swarm Agent"
__description__ = "Comprehensive guard tests preventing regression in AIVillage critical fixes"