apiVersion: apps/v1
kind: Deployment
metadata:
  name: aivillage-hyperag-mcp
  namespace: aivillage-production
  labels:
    app: aivillage-hyperag-mcp
    component: mcp-server
    slot: blue
spec:
  replicas: 2
  selector:
    matchLabels:
      app: aivillage-hyperag-mcp
      slot: blue
  template:
    metadata:
      labels:
        app: aivillage-hyperag-mcp
        component: mcp-server
        slot: blue
    spec:
      containers:
      - name: hyperag-mcp
        image: ghcr.io/aivillage/hyperag-mcp:latest
        ports:
        - containerPort: 8765
        env:
        - name: MCP_SERVER_PORT
          valueFrom:
            configMapKeyRef:
              name: aivillage-config
              key: MCP_SERVER_PORT
        - name: NEO4J_URI
          valueFrom:
            configMapKeyRef:
              name: aivillage-config
              key: NEO4J_URI
        - name: REDIS_HOST
          valueFrom:
            configMapKeyRef:
              name: aivillage-config
              key: REDIS_HOST
        - name: QDRANT_HOST
          valueFrom:
            configMapKeyRef:
              name: aivillage-config
              key: QDRANT_HOST
        envFrom:
        - configMapRef:
            name: aivillage-config
        - secretRef:
            name: aivillage-secrets
        livenessProbe:
          httpGet:
            path: /health
            port: 8765
          initialDelaySeconds: 60
          periodSeconds: 30
        readinessProbe:
          httpGet:
            path: /health
            port: 8765
          initialDelaySeconds: 30
          periodSeconds: 10
        resources:
          requests:
            memory: "512Mi"
            cpu: "300m"
          limits:
            memory: "1Gi"
            cpu: "800m"
        securityContext:
          allowPrivilegeEscalation: false
          runAsNonRoot: true
          runAsUser: 65534
          readOnlyRootFilesystem: true
          capabilities:
            drop:
            - ALL
        volumeMounts:
        - name: tmp-volume
          mountPath: /tmp
      volumes:
      - name: tmp-volume
        emptyDir: {}
---
apiVersion: v1
kind: Service
metadata:
  name: aivillage-hyperag-mcp
  namespace: aivillage-production
spec:
  selector:
    app: aivillage-hyperag-mcp
  ports:
  - name: mcp
    port: 8765
    targetPort: 8765
  type: ClusterIP
