apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: aivillage-neo4j
  namespace: aivillage-production
spec:
  serviceName: "aivillage-neo4j"
  replicas: 1
  selector:
    matchLabels:
      app: aivillage-neo4j
  template:
    metadata:
      labels:
        app: aivillage-neo4j
        component: graph-database
    spec:
      containers:
      - name: neo4j
        image: neo4j:5.11-community
        ports:
        - containerPort: 7474
        - containerPort: 7687
        env:
        - name: NEO4J_AUTH
          value: "$(NEO4J_USER)/$(NEO4J_PASSWORD)"
        - name: NEO4J_USER
          valueFrom:
            configMapKeyRef:
              name: aivillage-config
              key: NEO4J_USER
        - name: NEO4J_PASSWORD
          valueFrom:
            secretKeyRef:
              name: aivillage-secrets
              key: NEO4J_PASSWORD
        - name: NEO4J_PLUGINS
          value: '["apoc"]'
        - name: NEO4J_apoc_export_file_enabled
          value: "true"
        - name: NEO4J_apoc_import_file_enabled
          value: "true"
        - name: NEO4J_apoc_import_file_use__neo4j__config
          value: "true"
        - name: NEO4J_ACCEPT_LICENSE_AGREEMENT
          value: "yes"
        - name: NEO4J_dbms_memory_heap_initial__size
          value: "512m"
        - name: NEO4J_dbms_memory_heap_max__size
          value: "2G"
        volumeMounts:
        - name: neo4j-data
          mountPath: /data
        - name: neo4j-logs
          mountPath: /logs
        - name: neo4j-import
          mountPath: /var/lib/neo4j/import
        - name: neo4j-plugins
          mountPath: /plugins
        livenessProbe:
          exec:
            command:
            - cypher-shell
            - -u
            - $(NEO4J_USER)
            - -p
            - $(NEO4J_PASSWORD)
            - "MATCH (n) RETURN count(n)"
          initialDelaySeconds: 60
          periodSeconds: 30
        readinessProbe:
          exec:
            command:
            - cypher-shell
            - -u
            - $(NEO4J_USER)
            - -p
            - $(NEO4J_PASSWORD)
            - "MATCH (n) RETURN count(n)"
          initialDelaySeconds: 30
          periodSeconds: 10
        resources:
          requests:
            memory: "1Gi"
            cpu: "500m"
          limits:
            memory: "4Gi"
            cpu: "2"
  volumeClaimTemplates:
  - metadata:
      name: neo4j-data
    spec:
      accessModes: ["ReadWriteOnce"]
      resources:
        requests:
          storage: 20Gi
      storageClassName: fast-ssd
  - metadata:
      name: neo4j-logs
    spec:
      accessModes: ["ReadWriteOnce"]
      resources:
        requests:
          storage: 5Gi
      storageClassName: standard
  - metadata:
      name: neo4j-import
    spec:
      accessModes: ["ReadWriteOnce"]
      resources:
        requests:
          storage: 5Gi
      storageClassName: standard
  - metadata:
      name: neo4j-plugins
    spec:
      accessModes: ["ReadWriteOnce"]
      resources:
        requests:
          storage: 1Gi
      storageClassName: standard
---
apiVersion: v1
kind: Service
metadata:
  name: aivillage-neo4j
  namespace: aivillage-production
spec:
  selector:
    app: aivillage-neo4j
  ports:
  - name: http
    port: 7474
    targetPort: 7474
  - name: bolt
    port: 7687
    targetPort: 7687
  clusterIP: None