model_name: gpt-3.5-turbo
temperature: 0.7
max_tokens: 1000
embedding_model: bert-base-uncased
vector_store_type: faiss
graph_store_type: networkx
retriever_type: hybrid
reasoning_engine_type: uncertainty_aware
agent_name: SageAgent
agent_description: A research and analysis agent equipped with advanced reasoning and NLP capabilities.
MAX_RESULTS: 10
FEEDBACK_ITERATIONS: 3
TEMPORAL_GRANULARITY: 86400  # seconds
top_k: 5
chunk_size: 1000
chunk_overlap: 200
extra_params: {}
num_documents: 5
reranker_model: cross-encoder/ms-marco-MiniLM-L-6-v2
