# Cogment Deployment Configuration
# Production deployment settings for different environments

# Environment Configurations
environments:
  development:
    model_config: "cogment_config.yaml"
    batch_size: 4
    max_sequence_length: 1024
    device: "cuda:0"
    mixed_precision: true
    compile_model: false

  staging:
    model_config: "cogment_config.yaml"
    batch_size: 8
    max_sequence_length: 1536
    device: "cuda:0"
    mixed_precision: true
    compile_model: true

  production:
    model_config: "cogment_config.yaml"
    batch_size: 16
    max_sequence_length: 2048
    device: "auto"
    mixed_precision: true
    compile_model: true
    optimization_level: "O2"

# Model Serving Configuration
serving:
  # Server settings
  host: "0.0.0.0"
  port: 8000
  workers: 4
  max_concurrent_requests: 100
  request_timeout: 30

  # Model loading
  model_path: "./checkpoints/cogment/best.pt"
  warmup_requests: 10

  # Caching
  response_cache_size: 1000
  model_cache_enabled: true

  # Performance
  batch_inference: true
  max_batch_size: 32
  batch_timeout_ms: 50

# Resource Limits
resources:
  # Memory limits
  max_gpu_memory_gb: 24
  max_system_memory_gb: 64

  # Compute limits
  max_refinement_steps: 16
  timeout_per_request: 30

  # Model size constraints
  max_parameters: 26250000           # 5% above 25M target
  min_parameters: 23750000           # 5% below 25M target

# Monitoring and Logging
monitoring:
  # Metrics collection
  enable_metrics: true
  metrics_port: 9090
  metrics_interval: 10

  # Performance tracking
  track_latency: true
  track_throughput: true
  track_memory_usage: true
  track_gpu_utilization: true

  # Model-specific metrics
  track_refinement_steps: true
  track_ponder_costs: true
  track_memory_utilization: true
  track_grokking_indicators: true

# Health Checks
health_checks:
  # Readiness checks
  model_loaded: true
  gpu_available: true
  memory_sufficient: true

  # Liveness checks
  inference_working: true
  response_time_acceptable: true
  error_rate_acceptable: true

  # Thresholds
  max_response_time: 5.0
  max_error_rate: 0.05
  min_gpu_memory_free: 2.0

# Scaling Configuration
scaling:
  # Auto-scaling triggers
  enable_auto_scaling: true
  scale_up_threshold: 80            # CPU/GPU utilization %
  scale_down_threshold: 30

  # Scaling limits
  min_replicas: 1
  max_replicas: 10
  scale_up_cooldown: 300            # seconds
  scale_down_cooldown: 600

  # Load balancing
  load_balancer_strategy: "round_robin"
  health_check_interval: 30

# Security
security:
  # Authentication
  enable_auth: true
  api_key_required: true
  rate_limiting: true

  # Encryption
  tls_enabled: true
  tls_cert_path: "/certs/server.crt"
  tls_key_path: "/certs/server.key"

  # Request validation
  validate_input_length: true
  max_input_tokens: 4096
  content_filtering: true

# Backup and Recovery
backup:
  # Model checkpoints
  enable_checkpoint_backup: true
  backup_interval_hours: 6
  max_backups_retained: 10
  backup_storage_path: "/backups/cogment"

  # Configuration backup
  backup_configs: true
  config_backup_path: "/backups/configs"

# Integration Settings
integrations:
  # Logging
  log_level: "INFO"
  structured_logging: true
  log_format: "json"

  # Metrics backends
  prometheus_enabled: true
  grafana_dashboard: true

  # Tracing
  jaeger_enabled: false
  trace_sampling_rate: 0.1

  # Database
  metrics_db_url: "postgresql://user:pass@localhost/cogment_metrics"
  session_store: "redis://localhost:6379/0"

# Feature Flags
features:
  # Experimental features
  adaptive_batch_size: true
  dynamic_sequence_length: true
  memory_optimization: true

  # Model features
  enable_grokfast_serving: false     # Usually disabled in production
  enable_deep_supervision: false     # Training-time feature
  enable_consistency_checks: true

  # Performance features
  torch_compile: true
  tensor_parallelism: false
  pipeline_parallelism: false

# Error Handling
error_handling:
  # Retry configuration
  max_retries: 3
  retry_backoff: "exponential"
  base_delay: 1.0
  max_delay: 10.0

  # Fallback behavior
  enable_fallback_model: false
  fallback_model_path: "./checkpoints/fallback/model.pt"

  # Error reporting
  error_tracking_enabled: true
  error_notification_webhook: null

  # Recovery
  auto_restart_on_oom: true
  auto_restart_on_crash: true
  max_restart_attempts: 5
