# Frontier Curriculum Engine Configuration

# OpenRouter API Settings
openrouter:
  api_key: ${OPENROUTER_API_KEY}  # Set via environment variable
  default_model: "anthropic/claude-3-5-sonnet-20241022"
  rpm_limit: 60
  max_retries: 5
  base_delay: 1.0
  max_delay: 60.0

# Cache and Storage
storage:
  cache_dir: ".forge/cache"
  database: "frontier.sqlite"
  cost_log: "costs.jsonl"

# Curriculum Parameters
curriculum:
  # Edge-of-chaos target band
  target_accuracy_low: 0.55
  target_accuracy_high: 0.75

  # Problem generation
  problem_budget: 1000
  variant_rate: 0.30

  # Domain settings
  default_domain: "coding-python"

  # Mastery tracking
  mastery_threshold: 3  # Need 3 distinct variant passes
  stall_threshold: 5    # Max attempts before considering stalled

# Model Selection by Component
models:
  edge_finder: "anthropic/claude-3-5-sonnet-20241022"
  problem_generator: "anthropic/claude-3-5-sonnet-20241022"
  variant_synthesizer: "openai/gpt-4o-mini"
  grader: "anthropic/claude-3-5-haiku-20241022"
  hint_generator: "openai/gpt-4o-mini"
  mastery_policy: "openai/gpt-4o-mini"
  controller: "openai/gpt-4o-mini"
  conductor: "anthropic/claude-3-5-sonnet-20241022"

# Temperature Settings
temperature:
  edge_finder: 0.3
  problem_generator: 0.7
  variant_synthesizer: 0.8
  grader: 0.1
  hint_generator: 0.5
  mastery_policy: 0.2
  controller: 0.1
  conductor: 0.3

# Token Limits
max_tokens:
  edge_finder: 4096
  problem_generator: 4096
  variant_synthesizer: 2048
  grader: 1024
  hint_generator: 512
  mastery_policy: 1024
  controller: 1024
  conductor: 2048

# CLI Integration
cli:
  default_output_dir: "curriculum_output"
  checkpoint_frequency: 100
  log_level: "INFO"

# Integration with Forge Train Loop
integration:
  metrics_tracking: true
  wandb_logging: true
  checkpoint_integration: true
