_wandb:
    value:
        cli_version: 0.21.0
        e:
            015mb6h4a5k5pps8rnwswa1osyxw82vz:
                args:
                    - --frontier-api-key
                    - dummy-key
                    - --device
                    - cpu
                    - --skip-download
                    - --quick
                codePath: run_full_agent_forge.py
                codePathLocal: run_full_agent_forge.py
                cpu_count: 6
                cpu_count_logical: 12
                cudaVersion: "12.9"
                disk:
                    /:
                        total: "511358005248"
                        used: "470706786304"
                email: dydavidyoussef@gmail.com
                executable: C:\Users\17175\Desktop\AIVillage\evomerge_env\Scripts\python.exe
                git:
                    commit: 46e3ae8058c3758a2eb400e388f3b227c0fa65b2
                    remote: https://github.com/DNYoussef/AIVillage.git
                gpu: NVIDIA GeForce RTX 2060 SUPER
                gpu_count: 1
                gpu_nvidia:
                    - architecture: Turing
                      cudaCores: 2176
                      memoryTotal: "8589934592"
                      name: NVIDIA GeForce RTX 2060 SUPER
                      uuid: GPU-246bf774-04ba-64e4-c871-c6bc2059f08b
                host: DESKTOP-I78AK0M
                memory:
                    total: "17063505920"
                os: Windows-10-10.0.19045-SP0
                program: C:\Users\17175\Desktop\AIVillage\run_full_agent_forge.py
                python: CPython 3.12.5
                root: C:\Users\17175\Desktop\AIVillage\wandb
                startedAt: "2025-07-25T04:10:03.090980Z"
                writerId: 015mb6h4a5k5pps8rnwswa1osyxw82vz
        m: []
        python_version: 3.12.5
        t:
            "1":
                - 1
                - 5
                - 11
                - 49
                - 51
                - 53
                - 71
                - 75
                - 95
                - 105
            "2":
                - 1
                - 5
                - 11
                - 49
                - 51
                - 53
                - 71
                - 75
                - 95
                - 105
            "3":
                - 15
                - 16
            "4": 3.12.5
            "5": 0.21.0
            "6": 4.45.2
            "8":
                - 3
            "12": 0.21.0
            "13": windows-amd64
base_models:
    value:
        - DeepSeek-R1-Distill-Qwen-1.5B
        - Nemotron-Research-Reasoning-Qwen-1.5B
        - Qwen2-1.5B-Instruct
config:
    value:
        base_models:
            - DeepSeek-R1-Distill-Qwen-1.5B
            - Nemotron-Research-Reasoning-Qwen-1.5B
            - Qwen2-1.5B-Instruct
        checkpoint_dir: C:\Users\17175\Desktop\AIVillage\forge_checkpoints
        checkpoint_frequency: 1
        detect_stubs: true
        enabled_phases:
            - EVOMERGE
            - GEOMETRY
            - SELF_MODELING
            - PROMPT_BAKING
            - COMPRESSION
            - ADAS
        fail_fast: false
        max_memory_gb: 16
        max_phase_duration_minutes: 120
        output_dir: C:\Users\17175\Desktop\AIVillage\agent_forge_outputs
        retry_attempts: 3
        stub_keywords:
            - NotImplementedError
            - pass
            - TODO
            - FIXME
            - placeholder
            - raise NotImplementedError
            - return None
        wandb_job_type: orchestrator
        wandb_project: agent-forge
        wandb_tags:
            - pipeline
            - orchestrator
discovered_phases:
    value: []
enabled_phases:
    value:
        - evomerge
        - geometry
        - self_modeling
        - prompt_baking
        - compression
        - adas
run_id:
    value: b47b9c14-7510-4440-9a82-5611d602517e
