alerts:
  success_rate_threshold: 95.0
  performance_degradation: 1.5  # 50% slower
  flaky_test_threshold: 0.2
  consecutive_failures: 3

channels:
  - type: "log"
    path: "monitoring/alerts.log"
  
  # Uncomment and configure for GitHub integration
  # - type: "github"
  #   repo: "DNYoussef/AIVillage"
  #   labels: ["test-degradation", "automated"]
  
  # Uncomment and configure for webhook alerts (Discord/Slack)
  # - type: "webhook"
  #   url: "${ALERT_WEBHOOK_URL}"
  
  # Uncomment and configure for email alerts
  # - type: "email"
  #   smtp_server: "smtp.gmail.com"
  #   smtp_port: 587
  #   username: "alerts@example.com"
  #   to_emails: ["dev-team@example.com"]