global:
  scrape_interval: 15s
  evaluation_interval: 15s
rule_files:
  - alerts.yml

scrape_configs:
  - job_name: 'ai-village-services'
    dns_sd_configs:
      - names: ['tasks.ai-village']
        type: A
        port: 8000
    relabel_configs:
      - source_labels: [__meta_docker_container_label_prometheus_scrape]
        regex: 'true'
        action: keep
      - source_labels: [__meta_docker_container_label_prometheus_port]
        target_label: __address__
        replacement: '$1'
      - source_labels: [__meta_docker_container_label_service_name]
        target_label: service
