name: Test Failure
description: Track a known test failure or architectural limitation
title: "[TEST] "
labels: ["test-failure", "known-issue"]
body:
  - type: input
    id: test_path
    attributes:
      label: Test Path
      description: Full path to failing test (e.g., tests/compression/test_stage1.py::test_bitnet)
      placeholder: tests/module/test_file.py::test_function
    validations:
      required: true

  - type: textarea
    id: failure_reason
    attributes:
      label: Failure Reason
      description: Why does this test fail? Include error messages if relevant.
      placeholder: "Test fails because..."
    validations:
      required: true

  - type: dropdown
    id: category
    attributes:
      label: Category
      description: What type of issue is this?
      options:
        - Architectural Limitation
        - Missing Dependency
        - Performance Constraint
        - External Service Dependency
        - Configuration Issue
        - Environment-Specific
        - Other
    validations:
      required: true

  - type: dropdown
    id: test_type
    attributes:
      label: Test Type
      description: What type of test is this?
      options:
        - Unit Test
        - Integration Test
        - Performance Test
        - Canary Test
        - End-to-End Test
        - Other
    validations:
      required: true

  - type: checkboxes
    id: canary_test
    attributes:
      label: Canary Test
      description: Is this test serving as an architectural canary?
      options:
        - label: This test monitors for architectural changes
        - label: This test should alert when it unexpectedly passes
        - label: This test represents a planned future feature

  - type: textarea
    id: impact
    attributes:
      label: Impact
      description: What functionality is affected by this failure?
      placeholder: "This affects..."
    validations:
      required: true

  - type: textarea
    id: workarounds
    attributes:
      label: Workarounds
      description: Are there any workarounds or alternative approaches?
      placeholder: "Alternative approaches include..."

  - type: textarea
    id: resolution_plan
    attributes:
      label: Resolution Plan
      description: What steps are needed to resolve this issue?
      placeholder: |
        - [ ] Step 1: Research requirements
        - [ ] Step 2: Implement solution
        - [ ] Target: Q2 2025

  - type: dropdown
    id: priority
    attributes:
      label: Priority
      description: How important is resolving this issue?
      options:
        - Low (Canary/Future Feature)
        - Medium (Nice to Have)
        - High (Blocks Development)
        - Critical (Blocks Release)
    validations:
      required: true

  - type: textarea
    id: technical_details
    attributes:
      label: Technical Details
      description: Any additional technical context, stack traces, or implementation notes
      render: shell

  - type: textarea
    id: related_issues
    attributes:
      label: Related Issues
      description: Link to related issues, PRs, or discussions
      placeholder: "Related to #123, depends on #456"