# AIVillage Unified Gateway Configuration
# This file provides default configuration values that can be overridden by environment variables

# Environment settings
environment: development
debug: true

# Server configuration
gateway:
  host: "0.0.0.0"
  port: 8000
  request_timeout: 30
  health_check_timeout: 5

# Security settings
security:
  # Generate secure keys for production!
  api_key: "dev-gateway-key-12345"
  secret_key: "dev-secret-key-change-in-production"
  
  # Rate limiting
  rate_limit_requests: 100
  rate_limit_window: 60
  
  # CORS policy
  cors_origins:
    - "http://localhost:3000"
    - "http://localhost:8080"
    - "http://127.0.0.1:3000"
    - "http://127.0.0.1:8080"

# Downstream services
services:
  twin_url: "http://localhost:8001"
  agent_controller_url: "http://localhost:8002"
  knowledge_system_url: "http://localhost:8003"

# Feature flags
features:
  enable_metrics: true
  enable_file_upload: true
  enable_agent_proxy: true
  max_file_size: 10485760  # 10MB

# Performance tuning
performance:
  connection_pool_size: 100
  connection_pool_maxsize: 1000
  keepalive_timeout: 5

# Monitoring and logging
monitoring:
  log_level: "INFO"
  enable_request_logging: true
  enable_performance_logging: true
  health_check_interval: 30

# Production overrides (use environment-specific config files)
production:
  debug: false
  cors_origins:
    - "https://api.aivillage.com"
    - "https://app.aivillage.com"
  security:
    # These MUST be set via environment variables in production!
    api_key: ""  # Set via API_KEY env var
    secret_key: ""  # Set via SECRET_KEY env var