_wandb:
    value:
        cli_version: 0.21.0
        e:
            mbqvnii90txxji5nm83uvy6ocgr5vuco:
                cpu_count: 6
                cpu_count_logical: 12
                cudaVersion: "12.9"
                disk:
                    /:
                        total: "511358005248"
                        used: "470607249408"
                email: dydavidyoussef@gmail.com
                executable: C:\Users\17175\Desktop\AIVillage\evomerge_env\Scripts\python.exe
                git:
                    commit: 46e3ae8058c3758a2eb400e388f3b227c0fa65b2
                    remote: https://github.com/DNYoussef/AIVillage.git
                gpu: NVIDIA GeForce RTX 2060 SUPER
                gpu_count: 1
                gpu_nvidia:
                    - architecture: Turing
                      cudaCores: 2176
                      memoryTotal: "8589934592"
                      name: NVIDIA GeForce RTX 2060 SUPER
                      uuid: GPU-246bf774-04ba-64e4-c871-c6bc2059f08b
                host: DESKTOP-I78AK0M
                memory:
                    total: "17063505920"
                os: Windows-10-10.0.19045-SP0
                program: <python with no main file>
                python: CPython 3.12.5
                root: C:\Users\17175\Desktop\AIVillage
                startedAt: "2025-07-24T21:35:42.993949Z"
                writerId: mbqvnii90txxji5nm83uvy6ocgr5vuco
        m: []
        python_version: 3.12.5
        t:
            "1":
                - 105
            "2":
                - 105
            "3":
                - 16
            "4": 3.12.5
            "5": 0.21.0
            "8":
                - 3
            "12": 0.21.0
            "13": windows-amd64
adaptation_frequency:
    value: real_time
digital_twin_version:
    value: 1.0.0
grade_range:
    value: K-8
knowledge_tracking:
    value: concept_level
personalization_dimensions:
    value: 10
privacy_level:
    value: encrypted_local
real_time_adaptation:
    value: true
supported_languages:
    value:
        - en
        - es
        - hi
        - fr
        - ar
supported_learning_styles:
    value:
        - visual
        - auditory
        - kinesthetic
        - reading
