version: '3.8'

services:
  alertmanager:
    image: prom/alertmanager:v0.25.0
    container_name: aivillage-alertmanager
    restart: unless-stopped
    ports:
      - "9093:9093"
    volumes:
      - ./alertmanager.yml:/etc/alertmanager/alertmanager.yml:ro
      - alertmanager_data:/alertmanager
    command:
      - '--config.file=/etc/alertmanager/alertmanager.yml'
      - '--storage.path=/alertmanager'
      - '--web.external-url=http://localhost:9093'
      - '--web.route-prefix=/'
      - '--cluster.listen-address=0.0.0.0:9094'
      - '--log.level=info'
    networks:
      - aivillage-monitoring
    labels:
      - "aivillage.component=alerting"
      - "aivillage.service=alertmanager"

  webhook-receiver:
    image: alpine/curl:latest
    container_name: aivillage-webhook-receiver
    restart: unless-stopped
    ports:
      - "8080:8080"
    volumes:
      - ./webhook-server.py:/app/webhook-server.py:ro
    command: python3 /app/webhook-server.py
    networks:
      - aivillage-monitoring
    labels:
      - "aivillage.component=alerting"
      - "aivillage.service=webhook-receiver"

  # PagerDuty integration (optional)
  pagerduty-proxy:
    image: nginx:alpine
    container_name: aivillage-pagerduty-proxy
    restart: unless-stopped
    ports:
      - "8081:80"
    volumes:
      - ./pagerduty-proxy.conf:/etc/nginx/conf.d/default.conf:ro
    networks:
      - aivillage-monitoring
    depends_on:
      - alertmanager
    labels:
      - "aivillage.component=alerting"
      - "aivillage.service=pagerduty-proxy"

volumes:
  alertmanager_data:

networks:
  aivillage-monitoring:
    external: true
