{{- if .Values.qdrant.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "aivillage.fullname" . }}-qdrant
  labels:
    {{- include "aivillage.serviceLabels" (list "qdrant" .) | nindent 4 }}
spec:
  replicas: 1  # Single replica for now
  strategy:
    type: Recreate
  selector:
    matchLabels:
      {{- include "aivillage.serviceSelectorLabels" (list "qdrant" .) | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "aivillage.serviceSelectorLabels" (list "qdrant" .) | nindent 8 }}
    spec:
      securityContext:
        fsGroup: 1000
        runAsUser: 1000
        runAsGroup: 1000
        runAsNonRoot: true
      containers:
        - name: qdrant
          image: qdrant/qdrant:v1.7.3
          imagePullPolicy: IfNotPresent
          ports:
            - name: http
              containerPort: 6333
              protocol: TCP
            - name: grpc
              containerPort: 6334
              protocol: TCP
          env:
            - name: QDRANT__SERVICE__HTTP_PORT
              value: "6333"
            - name: QDRANT__SERVICE__GRPC_PORT
              value: "6334"
            - name: QDRANT__LOG_LEVEL
              value: "INFO"
            - name: QDRANT__STORAGE__STORAGE_PATH
              value: "/qdrant/storage"
            - name: QDRANT__SERVICE__MAX_REQUEST_SIZE_MB
              value: "32"
            - name: QDRANT__CLUSTER__ENABLED
              value: "false"
          livenessProbe:
            httpGet:
              path: /
              port: http
            initialDelaySeconds: 30
            periodSeconds: 10
            timeoutSeconds: 5
            failureThreshold: 3
          readinessProbe:
            httpGet:
              path: /readyz
              port: http
            initialDelaySeconds: 10
            periodSeconds: 5
            timeoutSeconds: 3
            failureThreshold: 3
          resources:
            {{- include "aivillage.resources" .Values.qdrant | nindent 12 }}
          volumeMounts:
            - name: qdrant-storage
              mountPath: /qdrant/storage
      volumes:
        - name: qdrant-storage
          {{- if .Values.qdrant.persistence.enabled }}
          persistentVolumeClaim:
            claimName: {{ include "aivillage.fullname" . }}-qdrant-storage
          {{- else }}
          emptyDir: {}
          {{- end }}
{{- end }}
