# AIVillage Development Configuration
# Optimized for local development with relaxed security

# Environment Settings
environment:
  type: development
  debug: true
  auto_reload: true
  mock_external_services: false

# Logging Configuration
logging:
  level: DEBUG
  format: structured
  file: ./logs/development/aivillage.log
  console_output: true
  rotation:
    size: 10MB
    retention_days: 7

# Database Configuration
database:
  evolution_metrics:
    path: ./data/development/evolution_metrics.db
    backend: sqlite
    wal_mode: true
    connection_timeout: 30

  digital_twin:
    path: ./data/development/digital_twin.db
    wal_mode: true
    backup_encryption: false

  rag:
    faiss_index_path: ./data/development/faiss_index
    chunk_store_path: ./data/development/chunk_store
    bm25_corpus_path: ./data/development/bm25_corpus

# API Configuration
api:
  authentication:
    enabled: false
    jwt_expiry_hours: 24

  cors:
    enabled: true
    origins: ["http://localhost:3000", "http://127.0.0.1:3000"]

  rate_limiting:
    enabled: false
    per_minute: 1000

  ports:
    digital_twin: 8080
    evolution_metrics: 8081
    rag_pipeline: 8082
    p2p_status: 8083

# P2P Networking
p2p:
  libp2p:
    host: 0.0.0.0
    port: 4001
    websocket_port: 4002
    private_key_file: ./config/development/libp2p_private_key

  mesh:
    max_peers: 20
    heartbeat_interval: 10
    connection_timeout: 30
    tls_enabled: false
    encryption_required: false

  transports:
    tcp_enabled: true
    websocket_enabled: true
    bluetooth_enabled: false
    wifi_direct_enabled: false
    file_transport_enabled: true
    file_transport_dir: /tmp/aivillage_mesh_dev

  discovery:
    mdns:
      enabled: true
      service_name: _aivillage_dev._tcp
      interval: 30
      ttl: 120

# RAG Pipeline
rag:
  embedding:
    model: paraphrase-MiniLM-L3-v2
    device: cpu
    batch_size: 16

  retrieval:
    vector_top_k: 20
    keyword_top_k: 20
    final_top_k: 10
    rerank_enabled: false

  chunking:
    size: 512
    overlap: 50

  cache:
    enabled: true
    l1_size: 64
    l2_enabled: false
    disk_cache_dir: /tmp/rag_cache_dev
    ttl_hours: 24

# Digital Twin
digital_twin:
  encryption:
    enabled: false  # Disabled for easier development
    key: ""  # Empty in development

  vault:
    path: ./data/development/vault

  privacy:
    coppa_compliant: false  # Relaxed for development
    ferpa_compliant: false
    gdpr_compliant: false

  profiles:
    max_count: 1000
    ttl_days: 30  # Shorter for development

  analytics:
    enabled: true
    telemetry_enabled: true

# Evolution System
evolution:
  metrics:
    flush_threshold: 20  # Lower for faster feedback
    flush_interval: 15
    storage_backend: sqlite

  orchestration:
    nightly_enabled: false  # Manual triggering in dev
    max_concurrent: 3

  analysis:
    plateau_detection: true
    improvement_tracking: true

# Mobile Configuration
mobile:
  p2p:
    enabled: true
    port_ranges:
      android_start: 4000
      android_end: 4005
      ios_start: 4005
      ios_end: 4010

  optimization:
    battery_aware: false
    offline_mode: true
    sync_interval: 600  # 10 minutes

# External Services
external_services:
  redis:
    enabled: false  # Optional in development
    url: redis://localhost:6379/0

  wandb:
    enabled: true
    project: aivillage-dev

  openai:
    enabled: false  # Optional

# Security (Relaxed for Development)
security:
  tls:
    enabled: false
    verify_peer: false

  headers:
    hsts_enabled: false
    csp_enabled: false
    frame_options: SAMEORIGIN

  backup:
    enabled: false
    encryption: false

# Performance Settings
performance:
  memory:
    max_total_mb: 1024
    max_faiss_mb: 256
    max_cache_mb: 128

  concurrency:
    max_queries: 5
    max_processes: 3

  timeouts:
    connection: 30
    read: 60
    write: 60

# Feature Flags
features:
  advanced_analytics: true
  multi_tenant: false
  blockchain_integration: false
  federated_learning: true  # Enable for development testing

# Development Tools
dev_tools:
  auto_reload: true
  debug_toolbar: true
  mock_p2p: false
  seed_data: true
  fast_startup: true

# Testing Configuration
testing:
  fast_mode: false
  mock_external_services: false
  disable_auth: true
  in_memory_db: false
