# SeedLM Compression Configuration Schema
# Advanced compression configuration for AI Village project

seedlm_config:
  # Global compression settings
  global:
    compression_preset: "balanced"  # Options: fast, balanced, quality
    memory_limit_gb: 16.0
    target_compression_ratio: 15.0
    max_accuracy_drop: 0.05
    enable_logging: true

  # Progressive encoding configuration
  progressive_encoding:
    base_quality: 0.3
    enhancement_layers: 3
    quality_increments: [0.2, 0.3, 0.2]
    enable_streaming: true
    bandwidth_adaptive: true

  # Layer-specific compression settings
  layer_specific:
    "*.attention.*":
      compression_level: 0.4  # Lower compression for attention layers
      block_size: 16
      latent_dim: 8
      priority: "quality"

    "*.mlp.*":
      compression_level: 0.7  # Higher compression for MLP layers
      block_size: 8
      latent_dim: 4
      priority: "compression"

    "*.embedding.*":
      compression_level: 0.3  # Preserve embeddings
      block_size: 32
      latent_dim: 16
      priority: "quality"

    "*.layer_norm.*":
      compression_level: 0.2  # Minimal compression for layer norm
      block_size: 32
      latent_dim: 16
      priority: "quality"

  # Advanced algorithm settings
  algorithm:
    compression_levels: [0.1, 0.3, 0.5, 0.7, 0.9]
    block_sizes: [4, 8, 16, 32]
    latent_dims: [2, 4, 8, 16]
    lfsr_taps: [16, 14, 13, 11]
    error_threshold: 0.001

    # Adaptive settings
    adaptive_block_sizing: true
    variance_threshold: 0.1
    importance_weighting: true

    # Multi-scale LFSR configuration
    multi_scale:
      seeds: [12345, 67890, 23456, 78901]
      tap_configs:
        - [16, 14, 13, 11]
        - [16, 15, 13, 4]
        - [16, 13, 12, 10]
        - [16, 14, 11, 9]
      orthogonalization: "gram_schmidt"

  # Performance optimization
  performance:
    batch_compression: true
    parallel_blocks: true
    memory_mapping: true
    cache_basis_matrices: true
    num_candidate_seeds: 64  # Reduced from 256 for speed

  # Quality control
  quality:
    enable_verification: true
    checksum_validation: true
    reconstruction_bounds: [0.001, 0.1]
    fallback_strategy: "reduce_compression"

  # Hardware-specific settings
  hardware:
    use_gpu_acceleration: false  # GPU acceleration currently disabled
    cuda_kernel_path: "kernels/seedlm.cu"
    memory_pool_size: "1GB"
    thread_pool_size: 4

# Integration settings for existing pipeline
integration:
  # BitNet integration
  bitnet:
    pre_compress: true
    post_bitnet_seedlm: true
    preserve_ternary: true

  # VPTQ integration
  vptq:
    post_compress: true
    hybrid_mode: "residual"
    vector_quantization: true

  # HyperFunction integration
  hyperfunction:
    trajectory_compression: true
    cluster_compression: 16
    enable_hyperfunc: true

# Presets for different use cases
presets:
  fast:
    target_compression_ratio: 8.0
    num_candidate_seeds: 16
    compression_levels: [0.3, 0.5, 0.7]
    enhancement_layers: 1

  balanced:
    target_compression_ratio: 15.0
    num_candidate_seeds: 64
    compression_levels: [0.1, 0.3, 0.5, 0.7, 0.9]
    enhancement_layers: 3

  quality:
    target_compression_ratio: 25.0
    num_candidate_seeds: 128
    compression_levels: [0.1, 0.2, 0.3, 0.5, 0.7, 0.9]
    enhancement_layers: 5
    max_accuracy_drop: 0.02

  research:
    target_compression_ratio: 30.0
    num_candidate_seeds: 256
    compression_levels: [0.05, 0.1, 0.2, 0.3, 0.5, 0.7, 0.9]
    enhancement_layers: 7
    max_accuracy_drop: 0.01
    enable_all_features: true

# Model architecture templates
model_templates:
  transformer:
    default_layer_config: "balanced"
    attention_compression: 0.4
    mlp_compression: 0.7
    embedding_compression: 0.3

  cnn:
    conv_compression: 0.6
    batch_norm_compression: 0.2
    linear_compression: 0.7

  rnn:
    recurrent_compression: 0.5
    linear_compression: 0.7
    embedding_compression: 0.3
