version: "1.0.0"
environment: "development"

components:
  task_manager:
    version: "1.0.0"
    enabled: true
    settings:
      batch_size: 5
      max_concurrent_tasks: 10
      task_timeout: 300
      retry_attempts: 3
      priority_levels:
        low: 1
        medium: 2
        high: 3
        critical: 4
    dependencies:
      - "error_handler"
      - "performance_monitor"

  planning:
    version: "1.0.0"
    enabled: true
    settings:
      mcts_iterations: 1000
      exploration_weight: 1.0
      max_depth: 10
      optimization_interval: 3600
      planning_timeout: 60
    dependencies:
      - "task_manager"
      - "knowledge_tracker"

  knowledge_tracker:
    version: "1.0.0"
    enabled: true
    settings:
      vector_store:
        type: "faiss"
        dimension: 768
        index_path: "data/vector_store"
      graph_store:
        type: "networkx"
        persistence: true
        backup_interval: 3600
      update_batch_size: 100
      confidence_threshold: 0.75
    dependencies:
      - "error_handler"

  error_handler:
    version: "1.0.0"
    enabled: true
    settings:
      log_level: "INFO"
      log_path: "logs/"
      error_thresholds:
        CRITICAL: 1
        ERROR: 5
        WARNING: 10
      retention_days: 30
      alert_channels:
        - "console"
        - "file"

  performance_monitor:
    version: "1.0.0"
    enabled: true
    settings:
      monitoring_interval: 60
      metrics_retention: 1000
      alert_thresholds:
        cpu_percent: 80.0
        memory_percent: 80.0
        operation_time: 5.0
      log_path: "logs/performance.log"

system:
  logging:
    level: "INFO"
    format: "%(asctime)s - %(name)s - %(levelname)s - %(message)s"
    handlers:
      - type: "file"
        filename: "logs/system.log"
        level: "INFO"
      - type: "console"
        level: "INFO"
  
  security:
    enable_authentication: true
    token_expiration: 3600
    allowed_origins:
      - "localhost"
      - "127.0.0.1"

  resources:
    max_memory: "4G"
    max_cpu_percent: 80
    temp_directory: "tmp/"
    data_directory: "data/"
