# AIVillage Feature Flags Configuration
#
# This file controls runtime feature toggles with canary rollouts and kill-switch capabilities.
# Changes to this file are automatically picked up within 60 seconds.
#
# Flag States:
# - enabled: Feature is fully enabled for all users in specified environments
# - disabled: Feature is disabled for all users
# - canary: Feature is enabled for canary_percentage of users or specific canary_users
# - kill_switch: Feature is emergency disabled (requires manual intervention)

flags:
  # RAG System Features
  - key: "advanced_rag_features"
    state: "canary"
    description: "Enable advanced RAG features like Bayesian trust networks and cognitive nexus"
    canary_percentage: 15.0
    canary_users:
      - "admin"
      - "tester"
      - "developer"
    environments:
      - "development"
      - "staging"

  - key: "rag_bayesian_trust"
    state: "enabled"
    description: "Enable Bayesian trust networks in RAG system"
    environments:
      - "development"
      - "staging"
      - "production"

  - key: "rag_cognitive_nexus"
    state: "canary"
    description: "Enable cognitive nexus for multi-perspective analysis"
    canary_percentage: 25.0
    environments:
      - "development"
      - "staging"

  # Agent System Features
  - key: "agent_forge_v2"
    state: "disabled"
    description: "Enable Agent Forge v2 pipeline with enhanced 7-phase architecture"
    environments:
      - "development"

  - key: "quiet_star_reflection"
    state: "enabled"
    description: "Enable Quiet-STaR reflection system for all agents"
    environments:
      - "development"
      - "staging"
      - "production"

  - key: "agent_self_modification"
    state: "canary"
    description: "Enable ADAS/Transformers² self-modification capabilities"
    canary_percentage: 10.0
    canary_users:
      - "admin"
      - "power_user"
    environments:
      - "development"
      - "staging"

  # P2P Networking Features
  - key: "p2p_mesh_networking"
    state: "enabled"
    description: "Enable BitChat P2P mesh networking"
    environments:
      - "all"

  - key: "betanet_transport"
    state: "enabled"
    description: "Enable BetaNet encrypted transport layer"
    environments:
      - "all"

  - key: "p2p_fog_computing"
    state: "canary"
    description: "Enable fog computing coordination across P2P network"
    canary_percentage: 20.0
    environments:
      - "development"
      - "staging"

  # Compression Features
  - key: "experimental_compression"
    state: "canary"
    description: "Enable experimental compression algorithms (BitNet, VPTQ, SeedLM)"
    canary_percentage: 5.0
    canary_users:
      - "admin"
      - "tester"
      - "compression_dev"
    environments:
      - "development"
      - "staging"

  - key: "mobile_compression"
    state: "enabled"
    description: "Enable mobile-optimized compression for edge devices"
    environments:
      - "all"

  - key: "hypercompression_pipeline"
    state: "disabled"
    description: "Enable 100x+ hypercompression pipeline (high risk)"
    kill_switch_reason: "Performance issues in staging environment"
    environments:
      - "development"

  # Security Features
  - key: "rbac_multi_tenant"
    state: "enabled"
    description: "Enable RBAC and multi-tenant isolation system"
    environments:
      - "staging"
      - "production"

  - key: "advanced_security_middleware"
    state: "canary"
    description: "Enable advanced security middleware with input validation"
    canary_percentage: 30.0
    environments:
      - "staging"
      - "production"

  - key: "pii_phi_compliance"
    state: "enabled"
    description: "Enable PII/PHI compliance management system"
    environments:
      - "production"

  # API Features
  - key: "api_versioning_v1"
    state: "enabled"
    description: "Enable API v1 versioning with deprecation middleware"
    environments:
      - "all"

  - key: "rate_limiting_advanced"
    state: "canary"
    description: "Enable advanced rate limiting with suspicious IP detection"
    canary_percentage: 40.0
    environments:
      - "staging"
      - "production"

  - key: "openapi_documentation"
    state: "enabled"
    description: "Enable OpenAPI documentation generation"
    environments:
      - "development"
      - "staging"

  # Mobile Features
  - key: "digital_twin_concierge"
    state: "canary"
    description: "Enable privacy-preserving digital twin concierge system"
    canary_percentage: 8.0
    canary_users:
      - "mobile_beta_user"
      - "privacy_tester"
    environments:
      - "development"
      - "staging"

  - key: "battery_thermal_optimization"
    state: "enabled"
    description: "Enable battery and thermal optimization for mobile devices"
    environments:
      - "all"

  - key: "surprise_based_learning"
    state: "canary"
    description: "Enable surprise-based learning for personal AI models"
    canary_percentage: 12.0
    environments:
      - "development"

  # Infrastructure Features
  - key: "global_south_offline"
    state: "enabled"
    description: "Enable Global South offline support with data budget management"
    environments:
      - "all"

  - key: "continuous_deployment"
    state: "canary"
    description: "Enable continuous deployment automation"
    canary_percentage: 50.0
    environments:
      - "staging"

  - key: "cost_optimization"
    state: "enabled"
    description: "Enable cloud cost analysis and optimization"
    environments:
      - "staging"
      - "production"

  # Debugging and Development
  - key: "debug_mode_enhanced"
    state: "enabled"
    description: "Enable enhanced debugging features for development"
    environments:
      - "development"

  - key: "performance_profiling"
    state: "canary"
    description: "Enable detailed performance profiling and metrics"
    canary_percentage: 100.0  # Enable for all development users
    environments:
      - "development"
      - "staging"

  - key: "integration_test_mocks"
    state: "enabled"
    description: "Enable integration test mocking for faster test execution"
    environments:
      - "development"
      - "testing"
