# AIVillage Services Configuration
# This file provides default configuration for all services

environment: development
debug: true

# Service-specific configurations
gateway:
  name: gateway
  version: "0.2.0"
  host: "0.0.0.0"
  port: 8000
  workers: 1
  timeout: 30
  max_request_size: 10485760  # 10MB
  cors_origins:
    - "http://localhost"
    - "http://localhost:3000"
    - "http://127.0.0.1"
  log_level: "INFO"

twin:
  name: twin
  version: "0.2.0"
  host: "0.0.0.0"
  port: 8001
  workers: 1
  timeout: 30
  max_request_size: 10485760  # 10MB
  cors_origins:
    - "http://localhost"
    - "http://localhost:3000"
  log_level: "INFO"

# Database configuration
database:
  host: "localhost"
  port: 5432
  name: "aivillage"
  user: "postgres"
  password: ""
  pool_size: 10
  ssl_mode: "prefer"

# Redis configuration
redis:
  host: "localhost"
  port: 6379
  password: ""
  database: 0
  pool_size: 10

# Security configuration
security:
  secret_key: "dev-secret-key-change-in-production"
  jwt_algorithm: "HS256"
  jwt_expiration: 3600  # 1 hour
  rate_limit_requests: 100
  rate_limit_window: 60  # 1 minute
  allowed_hosts:
    - "*"

# Monitoring configuration
monitoring:
  enable_metrics: true
  enable_tracing: false
  metrics_port: 9090
  health_check_interval: 30
  log_format: "json"

# AI/ML configuration
ai:
  model_name: "gpt-4"
  max_tokens: 4096
  temperature: 0.7
  embedding_model: "sentence-transformers/all-MiniLM-L6-v2"
  vector_store_type: "faiss"
  max_context_length: 8192

# External service URLs
external_services:
  twin_url: "http://localhost:8001"
  gateway_url: "http://localhost:8000"
