{{- if .Values.qdrant.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "aivillage.fullname" . }}-qdrant
  labels:
    {{- include "aivillage.serviceLabels" (list "qdrant" .) | nindent 4 }}
spec:
  type: ClusterIP
  ports:
    - port: 6333
      targetPort: http
      protocol: TCP
      name: http
    - port: 6334
      targetPort: grpc
      protocol: TCP
      name: grpc
  selector:
    {{- include "aivillage.serviceSelectorLabels" (list "qdrant" .) | nindent 4 }}
{{- end }}
