# Promtail Configuration for AIVillage Log Collection
server:
  http_listen_port: 9080
  grpc_listen_port: 0

positions:
  filename: /tmp/positions.yaml

clients:
  - url: http://loki:3100/loki/api/v1/push

scrape_configs:
  # System logs
  - job_name: system-logs
    static_configs:
      - targets:
          - localhost
        labels:
          job: system-logs
          __path__: /var/log/*.log

  # Docker container logs
  - job_name: docker-containers
    docker_sd_configs:
      - host: unix:///var/run/docker.sock
        refresh_interval: 5s
    relabel_configs:
      - source_labels: ['__meta_docker_container_name']
        regex: '/aivillage-(.*)'
        target_label: 'container'
      - source_labels: ['__meta_docker_container_label_aivillage_component']
        target_label: 'component'
      - source_labels: ['__meta_docker_container_label_aivillage_service']
        target_label: 'service'
      - source_labels: ['__meta_docker_container_log_stream']
        target_label: 'stream'
    pipeline_stages:
      - json:
          expressions:
            timestamp: timestamp
            level: level
            message: message
            service: service
            trace_id: trace_id
            span_id: span_id
      - timestamp:
          source: timestamp
          format: RFC3339Nano
      - labels:
          level: level
          service: service
      - output:
          source: message

  # Agent Forge Pipeline logs
  - job_name: agent-forge-logs
    static_configs:
      - targets:
          - localhost
        labels:
          job: agent-forge
          component: ml-pipeline
          __path__: /var/log/aivillage/agent-forge/*.log
    pipeline_stages:
      - regex:
          expression: '(?P<timestamp>\d{4}-\d{2}-\d{2} \d{2}:\d{2}:\d{2},\d{3}) \[(?P<level>\w+)\] \[(?P<phase>\w+)\] (?P<message>.*)'
      - timestamp:
          source: timestamp
          format: '2006-01-02 15:04:05,000'
      - labels:
          level: level
          phase: phase

  # HyperRAG Memory System logs
  - job_name: hyperrag-logs
    static_configs:
      - targets:
          - localhost
        labels:
          job: hyperrag
          component: memory-system
          __path__: /var/log/aivillage/hyperrag/*.log
    pipeline_stages:
      - json:
          expressions:
            timestamp: timestamp
            level: level
            query_type: query_type
            collection: collection
            duration_ms: duration_ms
            message: message
      - timestamp:
          source: timestamp
          format: RFC3339
      - labels:
          level: level
          query_type: query_type
          collection: collection

  # P2P Mesh Network logs
  - job_name: p2p-mesh-logs
    static_configs:
      - targets:
          - localhost
        labels:
          job: p2p-mesh
          component: networking
          __path__: /var/log/aivillage/p2p/*.log
    pipeline_stages:
      - regex:
          expression: '(?P<timestamp>\d{4}-\d{2}-\d{2}T\d{2}:\d{2}:\d{2}Z) (?P<level>\w+) peer=(?P<peer_id>\w+) msg_type=(?P<msg_type>\w+) (?P<message>.*)'
      - timestamp:
          source: timestamp
          format: RFC3339
      - labels:
          level: level
          peer_id: peer_id
          msg_type: msg_type

  # API Gateway logs
  - job_name: api-gateway-logs
    static_configs:
      - targets:
          - localhost
        labels:
          job: api-gateway
          component: api-gateway
          __path__: /var/log/aivillage/gateway/*.log
    pipeline_stages:
      - regex:
          expression: '(?P<timestamp>\d{4}-\d{2}-\d{2} \d{2}:\d{2}:\d{2}) (?P<method>\w+) (?P<endpoint>\S+) (?P<status>\d{3}) (?P<duration_ms>\d+)ms (?P<message>.*)'
      - timestamp:
          source: timestamp
          format: '2006-01-02 15:04:05'
      - labels:
          method: method
          endpoint: endpoint
          status: status

  # Edge Computing logs
  - job_name: edge-computing-logs
    static_configs:
      - targets:
          - localhost
        labels:
          job: edge-computing
          component: edge-device
          __path__: /var/log/aivillage/edge/*.log
    pipeline_stages:
      - json:
          expressions:
            timestamp: timestamp
            level: level
            device_id: device_id
            task_type: task_type
            battery_level: battery_level
            message: message
      - timestamp:
          source: timestamp
          format: RFC3339
      - labels:
          level: level
          device_id: device_id
          task_type: task_type

  # Application error logs with special handling
  - job_name: error-logs
    static_configs:
      - targets:
          - localhost
        labels:
          job: error-logs
          severity: error
          __path__: /var/log/aivillage/errors/*.log
    pipeline_stages:
      - json:
          expressions:
            timestamp: timestamp
            level: level
            service: service
            error_type: error_type
            stack_trace: stack_trace
            trace_id: trace_id
            message: message
      - timestamp:
          source: timestamp
          format: RFC3339
      - labels:
          level: level
          service: service
          error_type: error_type
          trace_id: trace_id
