# Emergency Bypass Procedures Configuration
# Defines emergency bypass procedures for critical production deployments

emergency_procedures:
  # Emergency Bypass Configuration
  bypass:
    enabled: true
    requires_approval: true
    approval_levels:
      - security_lead
      - engineering_manager
      - production_owner

    # Token-based authorization
    token_validation:
      enabled: true
      token_expiry_hours: 2
      single_use: true
      audit_required: true

    # Bypass scenarios
    allowed_scenarios:
      - critical_security_patch
      - production_outage
      - zero_day_vulnerability
      - regulatory_compliance
      - customer_impact_severity_1

    # Restrictions during bypass
    restrictions:
      max_duration_hours: 8
      requires_monitoring: true
      requires_rollback_plan: true
      post_incident_review_required: true
      security_scan_required_after: true

  # Approval Workflow
  approval_workflow:
    security_lead:
      required: true
      contact: "security-lead@aivillage.com"
      escalation_minutes: 15

    engineering_manager:
      required: true
      contact: "engineering-manager@aivillage.com"
      escalation_minutes: 30

    production_owner:
      required: true
      contact: "production-owner@aivillage.com"
      escalation_minutes: 45

    # Emergency contacts
    emergency_contacts:
      primary: "emergency@aivillage.com"
      secondary: "on-call@aivillage.com"
      escalation: "cto@aivillage.com"

  # Monitoring and Alerting during Bypass
  monitoring:
    enhanced_monitoring: true
    alert_channels:
      - security-alerts
      - production-alerts
      - executive-alerts

    metrics:
      - deployment_success_rate
      - security_violation_count
      - performance_degradation
      - error_rate_increase
      - rollback_triggers

    thresholds:
      error_rate_max: 5.0  # percentage
      response_time_max: 2000  # milliseconds
      security_violations_max: 0
      rollback_trigger_error_rate: 10.0

  # Post-Incident Requirements
  post_incident:
    required_actions:
      - incident_report_creation
      - root_cause_analysis
      - security_review
      - process_improvement_plan
      - stakeholder_communication

    timeline:
      incident_report_hours: 24
      root_cause_analysis_days: 5
      security_review_days: 3
      improvement_plan_days: 10

    review_participants:
      - security_team
      - engineering_team
      - production_team
      - quality_assurance
      - compliance_officer

# Failure Handling Policies
failure_policies:
  # Security Gate Failures
  security_gate:
    critical_vulnerabilities:
      action: block_deployment
      notification: immediate
      escalation: security_lead
      override_allowed: false

    high_vulnerabilities:
      action: require_approval
      notification: immediate
      escalation: engineering_manager
      override_allowed: true
      override_requires: security_approval

    secret_detection:
      action: block_deployment
      notification: immediate
      escalation: security_lead
      override_allowed: false
      remediation_required: true

  # Quality Gate Failures
  quality_gate:
    architecture_violations:
      action: warn_and_continue
      notification: delayed
      escalation: tech_lead
      override_allowed: true

    test_failures:
      action: block_deployment
      notification: immediate
      escalation: engineering_manager
      override_allowed: true
      override_requires: qa_approval

    coverage_threshold:
      action: warn_and_continue
      notification: delayed
      escalation: tech_lead
      override_allowed: true

  # Infrastructure Failures
  infrastructure:
    deployment_failure:
      action: automatic_rollback
      notification: immediate
      escalation: production_team
      retry_attempts: 3
      retry_delay_minutes: 5

    health_check_failure:
      action: automatic_rollback
      notification: immediate
      escalation: production_team
      timeout_minutes: 10

    performance_degradation:
      action: monitor_and_alert
      notification: immediate
      escalation: performance_team
      threshold_minutes: 15

# Compliance and Audit
compliance:
  audit_requirements:
    emergency_bypass:
      log_retention_years: 7
      audit_trail_required: true
      compliance_review_required: true
      regulatory_notification: true

    security_violations:
      incident_classification: true
      regulatory_reporting: true
      customer_notification_required: false
      legal_review_threshold: "high"

    quality_violations:
      trend_analysis_required: true
      process_improvement_tracking: true
      customer_impact_assessment: false

  # Reporting Requirements
  reporting:
    emergency_incidents:
      frequency: immediate
      recipients: [security_team, executive_team, compliance_officer]
      format: structured_incident_report

    monthly_summary:
      frequency: monthly
      recipients: [engineering_leadership, security_team, compliance_officer]
      metrics: [bypass_frequency, security_violations, quality_trends]

    quarterly_review:
      frequency: quarterly
      recipients: [executive_team, board_risk_committee]
      scope: [policy_effectiveness, incident_trends, process_improvements]

# Communication Templates
communication_templates:
  emergency_bypass_notification:
    subject: "EMERGENCY: Production Deployment Bypass Activated"
    priority: critical
    template: |
      Emergency deployment bypass has been activated for AIVillage production systems.

      Bypass Details:
      - Timestamp: {timestamp}
      - Approver: {approver}
      - Scenario: {scenario}
      - Duration: {duration}
      - Commit: {commit_sha}

      Monitoring: Enhanced monitoring is now active
      Next Steps: Post-incident review required within 24 hours

      Contact: {emergency_contact}

  security_violation_alert:
    subject: "SECURITY ALERT: Deployment Gate Violation"
    priority: high
    template: |
      Security violation detected in deployment pipeline.

      Violation Details:
      - Type: {violation_type}
      - Severity: {severity}
      - Pipeline: {pipeline}
      - Commit: {commit_sha}

      Action Taken: {action_taken}
      Remediation Required: {remediation_required}

      Contact Security Team: {security_contact}

# Integration Settings
integrations:
  slack:
    enabled: true
    channels:
      emergency: "#emergency-deployments"
      security: "#security-alerts"
      production: "#production-alerts"

  pagerduty:
    enabled: true
    service_keys:
      security: "security-service-key"
      production: "production-service-key"

  email:
    enabled: true
    smtp_server: "smtp.aivillage.com"
    from_address: "alerts@aivillage.com"

  jira:
    enabled: true
    project_key: "SEC"
    issue_type: "Security Incident"

  github:
    enabled: true
    create_issues: true
    label_prefix: "security/"
