groups:
  - name: scion-production
    rules:
      - alert: AEADAuthFailures
        expr: increase(aead_auth_failures_total[5m]) > 0
        for: 5m
        labels:
          severity: critical
        annotations:
          description: AEAD authentication failures detected
      - alert: ReplayDropsSpike
        expr: increase(replay_drops_total[5m]) > 100
        for: 5m
        labels:
          severity: warning
        annotations:
          description: Replay drop count spiked above 100 in 5m
      - alert: KeyRotationStall
        expr: (time() - key_rotation_timestamp_seconds) > 86400
        for: 0m
        labels:
          severity: warning
        annotations:
          description: No key rotation in the last 24h
      - alert: DecryptLatencyHigh
        expr: |-
          histogram_quantile(
            0.95,
            sum(rate(decrypt_latency_seconds_bucket[5m])) by (le)
          )
            > 2 * decrypt_latency_seconds:p95_baseline
        for: 5m
        labels:
          severity: warning
        annotations:
          description: Decrypt p95 latency exceeds 2x baseline
