_wandb:
    value:
        cli_version: 0.21.0
        e:
            axqw1zvkp60ljjr95tqdctred6qpgqtf:
                cpu_count: 6
                cpu_count_logical: 12
                cudaVersion: "12.9"
                disk:
                    /:
                        total: "511358005248"
                        used: "471898624000"
                email: dydavidyoussef@gmail.com
                executable: C:\Users\17175\Desktop\AIVillage\evomerge_env\Scripts\python.exe
                git:
                    commit: 87d8fbfc819d110239f6e8ee117c03e65aca4bad
                    remote: https://github.com/DNYoussef/AIVillage.git
                gpu: NVIDIA GeForce RTX 2060 SUPER
                gpu_count: 1
                gpu_nvidia:
                    - architecture: Turing
                      cudaCores: 2176
                      memoryTotal: "8589934592"
                      name: NVIDIA GeForce RTX 2060 SUPER
                      uuid: GPU-246bf774-04ba-64e4-c871-c6bc2059f08b
                host: DESKTOP-I78AK0M
                memory:
                    total: "17063505920"
                os: Windows-10-10.0.19045-SP0
                program: <python with no main file>
                python: CPython 3.12.5
                root: C:\Users\17175\Desktop\AIVillage
                startedAt: "2025-07-25T14:55:56.676213Z"
                writerId: axqw1zvkp60ljjr95tqdctred6qpgqtf
        m: []
        python_version: 3.12.5
        t:
            "1":
                - 1
                - 5
                - 11
                - 49
                - 51
                - 53
                - 71
                - 75
                - 95
                - 105
            "2":
                - 1
                - 5
                - 11
                - 49
                - 51
                - 53
                - 71
                - 75
                - 95
                - 105
            "3":
                - 2
                - 15
                - 16
                - 24
            "4": 3.12.5
            "5": 0.21.0
            "6": 4.45.2
            "8":
                - 3
            "12": 0.21.0
            "13": windows-amd64
curriculum_levels:
    value: 2
device:
    value: auto
domain:
    value: coding_mathematics
dream_enhancement:
    value: true
enable_geometric_awareness:
    value: true
enable_self_modification:
    value: true
grokking_detection:
    value: true
mixed_precision:
    value: true
modification_safety_bounds:
    value:
        max_temperature_change: 0.5
        max_weight_change: 0.1
        rollback_threshold: 0.95
optimal_model_path:
    value: D:/AgentForge/results_50gen
output_dir:
    value: D:/AgentForge/magi_output_test
questions_per_level:
    value: 5
seed:
    value: 42
sleep_cycle_frequency:
    value: 500
specialization_areas:
    value:
        - python_programming
        - algorithm_design
        - mathematical_proofs
        - computational_complexity
        - data_structures
        - numerical_analysis
total_questions:
    value: 10000
wandb_entity:
    value: null
wandb_project:
    value: agent-forge-magi
wandb_tags:
    value:
        - magi
        - specialization
        - self-aware
weight_visualization_freq:
    value: 100
