name: Agent Forge Pipeline Testing

on:
  push:
    branches: [ main, develop ]
    paths:
      - 'agent_forge/**'
      - 'scripts/**'
      - '.github/workflows/agent-forge-pipeline.yml'
  pull_request:
    branches: [ main ]
    paths:
      - 'agent_forge/**'
      - 'scripts/**'

env:
  PYTHON_VERSION: "3.9"
  CUDA_VERSION: "11.8"

jobs:
  lint-and-test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: ${{ env.PYTHON_VERSION }}

    - name: Cache pip dependencies
      uses: actions/cache@v3
      with:
        path: ~/.cache/pip
        key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
        restore-keys: |
          ${{ runner.os }}-pip-

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install flake8 pytest pytest-cov black isort
        pip install -r agent_forge/requirements.txt

    - name: Lint with flake8
      run: |
        # Stop build if there are Python syntax errors or undefined names
        flake8 agent_forge --count --select=E9,F63,F7,F82 --show-source --statistics
        # Treat all errors as warnings
        flake8 agent_forge --count --exit-zero --max-complexity=10 --max-line-length=88 --statistics

    - name: Format check with Black
      run: |
        black --check --diff agent_forge/

    - name: Import sorting check with isort
      run: |
        isort --check-only --diff agent_forge/

    - name: Test with pytest
      run: |
        pytest agent_forge/evomerge/tests/ -v --cov=agent_forge --cov-report=xml

    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v3
      with:
        file: ./coverage.xml

  integration-test:
    runs-on: ubuntu-latest
    needs: lint-and-test

    steps:
    - uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: ${{ env.PYTHON_VERSION }}

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r agent_forge/requirements.txt

    - name: Test Phase Discovery
      run: |
        cd agent_forge
        python -c "
        from forge_orchestrator import ForgeOrchestrator, OrchestratorConfig
        config = OrchestratorConfig(detect_stubs=True)
        orchestrator = ForgeOrchestrator(config)
        discovered = orchestrator.discover_phase_modules()
        print(f'Discovered {len(discovered)} phases')
        for phase_type, module in discovered.items():
            print(f'  {phase_type.value}: {module.module_path} (stub: {module.is_stub})')
        assert len(discovered) >= 3, 'Should discover at least 3 phases'
        "

    - name: Test Configuration Validation
      run: |
        cd agent_forge/evomerge
        python -c "
        from config import create_default_config
        config = create_default_config()
        print('Configuration validation passed')
        print(f'Models: {[m.name for m in config.models]}')
        print(f'Evolution generations: {config.evolution_settings.num_generations}')
        "

    - name: Mini Benchmark Test
      run: |
        cd agent_forge
        python -c "
        import asyncio
        from enhanced_orchestrator import EnhancedOrchestrator, create_enhanced_config

        async def mini_test():
            config = create_enhanced_config()
            config.enabled_phases = []  # Don't run actual phases in CI
            orchestrator = EnhancedOrchestrator(config)

            # Test phase discovery
            discovered = orchestrator.discover_phase_modules()
            print(f'Mini test: Discovered {len(discovered)} phases')

            return len(discovered)

        result = asyncio.run(mini_test())
        assert result >= 3, f'Expected at least 3 phases, got {result}'
        print('Mini benchmark test passed')
        "

  benchmark-regression:
    runs-on: ubuntu-latest
    needs: lint-and-test
    if: github.event_name == 'pull_request'

    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0  # Need full history for comparison

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: ${{ env.PYTHON_VERSION }}

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r agent_forge/requirements.txt

    - name: Benchmark Phase Discovery Performance
      run: |
        cd agent_forge
        python -c "
        import time
        from forge_orchestrator import ForgeOrchestrator, OrchestratorConfig

        # Benchmark phase discovery
        start_time = time.time()
        config = OrchestratorConfig(detect_stubs=True)
        orchestrator = ForgeOrchestrator(config)
        discovered = orchestrator.discover_phase_modules()
        discovery_time = time.time() - start_time

        print(f'Phase discovery took {discovery_time:.3f} seconds')
        print(f'Discovered {len(discovered)} phases')

        # Check for reasonable performance (should be under 5 seconds)
        assert discovery_time < 5.0, f'Phase discovery too slow: {discovery_time:.3f}s'

        # Check that we found the expected phases
        expected_phases = ['evomerge', 'geometry', 'compression']
        found_phases = [p.value for p in discovered.keys()]

        for expected in expected_phases:
            assert any(expected in found for found in found_phases), f'Missing expected phase: {expected}'

        print('Benchmark regression test passed')
        "

    - name: Comment PR with Benchmark Results
      if: github.event_name == 'pull_request'
      uses: actions/github-script@v6
      with:
        script: |
          const comment = `
          ## 🚀 Agent Forge Benchmark Results

          ### Phase Discovery Performance
          - Discovery completed successfully
          - Found expected core phases (evomerge, geometry, compression)
          - Performance within acceptable limits

          ### Integration Test Status
          ✅ Phase discovery functional
          ✅ Configuration validation passed
          ✅ Mini benchmark completed

          This PR is ready for merge from a testing perspective.
          `;

          github.rest.issues.createComment({
            issue_number: context.issue.number,
            owner: context.repo.owner,
            repo: context.repo.repo,
            body: comment
          });
