name: CI

on:
  push:
  pull_request:

jobs:
  quick-check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install essential tools
        run: |
          pip install ruff black

      - name: Critical Syntax Check
        run: |
          echo "Running critical syntax error checks..."
          ruff check src/ --select E9,F63,F7 --statistics || {
            echo "CRITICAL: Syntax errors found in src/"
            exit 1
          }
          echo "✅ Critical syntax check passed"

      - name: Undefined Names Check
        run: |
          echo "Checking for undefined names..."
          ruff check src/ --select F82,F821,F823 --statistics || {
            echo "❌ Undefined names found - these must be fixed"
            exit 1
          }
          echo "✅ Undefined names check passed"

      - name: Security Check
        run: |
          echo "Running security scan for critical issues..."
          ruff check src/ --select S106 --quiet || {
            echo "CRITICAL: Shell injection vulnerabilities found in src/"
            exit 1
          }
          echo "✅ Critical security check passed"

      - name: Extended Security Check
        run: |
          echo "Running extended security checks..."
          ruff check src/ --select S102,S105,S107,S108 --quiet || {
            echo "❌ Security warnings found - review and fix these issues"
            exit 1
          }
          echo "✅ Extended security check passed"

  extended-lint:
    runs-on: ubuntu-latest
    needs: quick-check
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install tools
        run: pip install ruff black isort

      - name: Style Check
        run: |
          echo "Running extended style checks..."
          ruff check . --select E,W,F,I,UP,B,C4 --statistics || {
            echo "❌ Style issues found - please fix these"
            exit 1
          }
          echo "✅ Style check passed"

      - name: Format Check
        run: |
          echo "Checking code formatting..."
          black --check --diff --line-length=120 . || {
            echo "❌ Formatting issues found - run 'black --line-length=120 .' to fix"
            exit 1
          }
          echo "✅ Format check passed"

  test:
    runs-on: ubuntu-latest
    needs: quick-check
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          pip install -r requirements.txt -r requirements-dev.txt -r requirements-test.txt

      - name: Basic Import Test
        run: |
          echo "Testing basic imports..."
          python -c "import sys; sys.path.insert(0, 'src'); print('✅ Python path configured')" || {
            echo "❌ Import test failed - check Python path configuration"
            exit 1
          }

      - name: Run available tests
        run: |
          echo "Running available tests..."
          pytest --tb=short -v || {
            echo "❌ Tests failed - fix failing tests before merging"
            exit 1
          }
          echo "✅ All tests passed"
