name: CI

on:
  pull_request:
    paths-ignore:
      - 'docs/**'
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 25
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - name: Install Poetry
        run: pip install poetry
      - name: Install dependencies
        run: |
          poetry install --no-interaction --no-root
          poetry run pip install ruff black mypy pytest pytest-cov
      - name: Ruff (lint)
        run: poetry run ruff .
      - name: Black (check only)
        run: poetry run black --check .
      - name: MyPy (type-check)
        run: poetry run mypy --install-types --non-interactive . || true
      - name: Pytest
        run: poetry run pytest -q --cov=.
      - name: Build docker image
        run: docker build -t atlantis-ai:ci .
