name: CI

on:
  push:
  pull_request:

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      - uses: actions/cache@v3
        with:
          path: |
            ~/.cache/pip
            ~/.cache/pre-commit
          key: ${{ runner.os }}-pip-${{ hashFiles('requirements.txt', 'requirements-dev.txt', 'requirements-test.txt') }}-pre-commit-${{ hashFiles('.pre-commit-config.yaml') }}
      - name: Install dependencies
        run: |
          pip install -r requirements.txt -r requirements-dev.txt -r requirements-test.txt
          pre-commit install-hooks
      - name: Run pre-commit
        run: pre-commit run --all-files

  test:
    runs-on: ubuntu-latest
    needs: lint
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      - uses: actions/cache@v3
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('requirements.txt', 'requirements-dev.txt', 'requirements-test.txt') }}
          restore-keys: ${{ runner.os }}-pip-
      - name: Install dependencies
        run: |
          pip install -r requirements.txt -r requirements-dev.txt -r requirements-test.txt
      - name: Run tests
        run: pytest --cov=src --cov-report=xml
      - uses: actions/upload-artifact@v3
        with:
          name: coverage
          path: coverage.xml
