name: Gate Integration Tests

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  gate-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - name: Install dependencies
        run: |
          pip install -r requirements.txt || true
          pip install pytest
      - name: Run gate integration tests
        run: pytest tests/workflow_test/test_gate_missing_outputs.py
