name: Nightly Cross-Platform

on:
  schedule:
    - cron: '0 2 * * *'  # 2 AM UTC daily
  workflow_dispatch:  # Allow manual trigger

jobs:
  cross-platform-test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]
        python: ['3.10', '3.11']
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python }}

      - name: Install core dependencies
        run: |
          pip install ruff black pytest
          pip install -r requirements.txt || echo "Requirements install failed, continuing..."
        continue-on-error: true

      - name: Critical checks
        run: |
          echo "Running critical syntax checks on ${{ matrix.os }} Python ${{ matrix.python }}"
          ruff check . --select E9,F63,F7,F82 --statistics || {
            echo "CRITICAL: Platform compatibility issues found"
            exit 1
          }

      - name: Platform compatibility test
        run: |
          echo "Testing basic imports and functionality..."
          python -c "import sys; sys.path.insert(0, 'src'); print(f'✅ Python {sys.version} on {sys.platform}')"
        continue-on-error: true

      - name: Security scan
        run: |
          echo "Running security scan..."
          ruff check . --select S102,S105,S106,S107,S108 --quiet || {
            echo "Security issues found on ${{ matrix.os }}"
            exit 1
          }
        continue-on-error: false
