name: Update repository stats

on:
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch:

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Install cloc
      run: sudo apt-get update && sudo apt-get install -y cloc
    - name: Run stats script
      run: python scripts/update_status.py
    - name: Commit changes
      run: |
        git config user.name 'github-actions'
        git config user.email 'actions@users.noreply.github.com'
        git add docs/status.md
        if git diff --cached --quiet; then echo 'No changes'; exit 0; fi
        git commit -m 'Update status' && git push
